### ISSUE TITLE
Package the zope.interface dependency

### ISSUE THREAD

**Issue by vbraun** [sagemath/sagenb#126]
Sage is moving away from ZODB3, which is the only thing requiring zope.interface in Sage. So when we eventually retire ZODB3, zope.interface will also be removed. But apparently twisted in the sagenb spkg depends on zope.interface, so you have to package the dependency yourself in the long run.

See also: http://trac.sagemath.org/10352

**Comment by kcrisman** [comment]
This was definitely fixed by that commit, yes.

```
$ ls sagenb-0.11.2
Babel-1.3.tar.gz		install_order
Flask-0.10.1.tar.gz		itsdangerous-0.24.tar.gz
Flask-AutoIndex-0.5.tar.gz	python-openid-2.2.5.zip
Flask-Babel-0.9.tar.gz		pytz-2013b.zip
Flask-OldSessions-0.10.tar.gz	sagenb-0.11.2.tar.gz
Flask-OpenID-1.2.4.tar.gz	speaklater-1.3.tar.gz
Flask-Silk-0.2.tar.gz		webassets-0.10.1.tar.gz
Twisted-14.0.2.tar.bz2		zope.interface-4.1.1.tar.gz
Werkzeug-0.9.6.tar.gz
```
