### ISSUE TITLE
introspection with evaluation hangs

### ISSUE THREAD

**Issue by kcrisman** [sagemath/sagenb#165]
See [Trac 11853](http://trac.sagemath.org/sage_trac/ticket/11853).   Jeroen gives the following steps to make it hang. Note it's evaluation, not tab-completion, that causes trouble:

If running locally, start with sage -n
Create new worksheet, call it GFhelp
In the worksheet, evaluate the following and wait for Sage to finish:
GF?
Close the worksheet
Reopen the worksheet GFhelp
Re-execute GF? by simply typing SHIFT-ENTER.

**Comment by novoselt** [comment]
No recent complaints about rendering documentation, don't recall when it got resolved...
