### ISSUE TITLE
Add clear instructions on how to enable LDAP

### ISSUE THREAD

**Issue by ppurka** [sagemath/sagenb#177]
@rmartinjak You use the LDAP authentication method. Can you add some clear instructions to the README or to some other file in the top level directory giving clear instructions on how to enable the LDAP functionality? I understand that one needs to install python-ldap, but a clear command by command instruction will be more helpful.

See this [support thread](https://groups.google.com/d/topic/sage-support/NlfiJt-OTpU/discussion)

**Comment by dimpase** [comment]
to summarise the common knowledge (assuming you do run this with openSSL - otherwise
there won't be much security for the setup) from sage-devel [thread](https://groups.google.com/d/msg/sage-devel/L4jPVz782SI/_-Q84Ze0AQAJ).

* sagenb server needs ldap2 and sasl2 headers and lib (on Debian: libldap2-dev and libsasl2-dev)
* run `./sage --pip install python-ldap && ./sage -b`

**Comment by dimpase** [comment]
Do we need to merge https://github.com/sagemath/sagenb/pull/347 ?

**Comment by kcrisman** [comment]
There was some slight "needs work" there, namely that the error message explicitly indicates that the username isn't in the system.  And of course someone should actually test it on a working install.  But yes it would be nice to merge that.

**Comment by jm58660** [comment]
I managed to get SageNB work with LDAP on SageMath 8.1 by those instructions. I had already ran `./sage -i openssl` and .`/sage -pip install pyopenssl` before that, don't know if they are needed.

Clearly some kind of filtering would be useful for some uses, like differentiating staff and studs. In perfect world we could even have different timeout and ulimit values for different user groups.

**Comment by dimpase** [comment]
Tere päevast/Hei päivä :-)

On Tue, Dec 12, 2017 at 10:32 AM, jm58660 <notifications@github.com> wrote:

> I managed to get SageNB work with LDAP on SageMath 8.1 by those
> instructions. I had already ran ./sage -i openssl and ./sage -pip install
> pyopenssl before that, don't know if they are needed.
>
> Clearly some kind of filtering would be useful for some uses, like
> differentiating staff and studs. In perfect world we could even have
> different timeout and ulimit values for different user groups.
>

You know how to  pull in pull requests to another repo, perhaps you can
try that pull request?

Let me know if you want commiting/merging  rights for this repo...

Dima
