### ISSUE TITLE
If MathJax is a Sage package, use that version

### ISSUE THREAD

**Issue by kcrisman** [sagemath/sagenb#258]
See http://trac.sagemath.org/ticket/17288 where to let MathJax work in the IPython notebook they add it as a standard package.  Unless we're really serious about doing sagenb as a separate project (which I have zero interest in) we might as well use it.  There it is commented

> I just gave a try, simply removing the mathjax directory in `local/lib/python2.7/site-packages/sagenb-*.egg/sagenb/data` and replacing it with a symlink  to `../../../../../../share/mathjax` seems to work well.

**Comment by novoselt** [comment]
I just got confused by MathJax 2.2 in my Sage-6.9 and my guess is that when I installed master sagenb rather than package shipped in Sage symlink trick stopped working. This is potentially a very confusing side effect. Any chance of completely removing MathJax from the notebook and somehow linking it with the Sage version in a more direct way?

**Comment by kcrisman** [comment]
> I just got confused by MathJax 2.2 in my Sage-6.9 and my guess is that
> when I installed master sagenb rather than package shipped in Sage symlink
> trick stopped working. This is potentially a very confusing side effect.
> Any chance of completely removing MathJax from the notebook and somehow
> linking it with the Sage version in a more direct way?
>
I have no objection to that but again I won't be able to try anything out
properly.  Especially when it comes to linking packages etc.  Do you have a
sense of why it would have not worked right?

**Comment by novoselt** [comment]
Well, the reason why SageNB is using MathJax from Sage is http://git.sagemath.org/sage.git/commit/?id=f90f7e1ae06e88e0d72a49a4f2d4351d4caaedf4
which deletes shipped MathJax and symlinks a new version. What we need is some way for SageNB to detect on its own where Sage's version is - then repository install will use it as well and there is no need for extra operations in Sage when installing. I am not sure, however, what's the proper way to implement this detection (or even an improper one, for that matter).
