### ISSUE TITLE
Publishing redirects to different worksheet if worksheet was shared

### ISSUE THREAD

**Issue by jdemeyer** [sagemath/sagenb#266]
After publishing (or re-publishing or un-publishing) a worksheet shared with somebody else, I get redirected to the worksheet of myself with the same number.

More precisely: I'm looking at the page `http://sage.ugent.be/home/Karsten.Naert/10/publish`. After clicking "Stop publishing", the action was successful, but after this I end up viewing `http://sage.ugent.be/home/J.Demeyer/10/publish`. Note the changed username!

**Comment by jdemeyer** [comment]
Please give it some time. I am not using the latest notebook on my production server.

**Comment by jdemeyer** [comment]
I would like to wait for Sage Trac 10057 in Sage 6.5 to upgrade the Sage server at my university. If Sage 6.5 has been released on 2 february, I will upgrade that week. Otherwise it will be september.

**Comment by jdemeyer** [comment]
Let me remind you about #32. Fixing that would make the upgrade easier for me.

**Comment by kcrisman** [comment]
@jdemeyer Thanks, see my comment there.

**Comment by jdemeyer** [comment]
This exact problem still happens with sagenb in Sage 6.8.

**Comment by jdemeyer** [comment]
Still happens in Sage 7.4.
