### ISSUE TITLE
Create server-specific cell execution directories

### ISSUE THREAD

**Issue by jasongrout** [sagemath/sagenb#32]
See http://trac.sagemath.org/sage_trac/ticket/11679 and http://groups.google.com/group/sage-notebook/browse_thread/thread/828211dbf2e40d80

**Comment by kcrisman** [comment]
@jdemeyer - can you create a branch based off of that patch (of yours) so I can more easily review it?

**Comment by kcrisman** [comment]
Does this deal with http://ask.sagemath.org/question/8649/overview-of-security-and-memory-management/ ?

**Comment by kcrisman** [comment]
Closed by #331.
