### ISSUE TITLE
User can see temp cell contents of other users

### ISSUE THREAD

**Issue by kcrisman** [sagemath/sagenb#326]
Here is another annoying thing, though not quite as bad as XSS possible issues.

> However when I do cat /tmp/_/_.py in the notebook (after setting language to "sh" of course), I get some cell contents of other users. Those files in /tmp belong to the main sage user, and have permissions rw-r--r--.

See the original report at [ask.sagemath](http://ask.sagemath.org/question/25337/notebook-how-to-prevent-that-users-can-access-cell-content-of-other-users/).  Of course, one would have to figure out which tmp file corresponds to which user or whatever, but it's still not even close to optimal.

**Comment by kcrisman** [comment]
@novoselt - would at least using @jdemeyer's solution help with http://ask.sagemath.org/question/8649/overview-of-security-and-memory-management/ ?

**Comment by jdemeyer** [comment]
> would at least using @jdemeyer's solution help with http://ask.sagemath.org/question/8649/overview-of-security-and-memory-management/ ?

The only good answer is: sagenb is insecure, live with it.

**Comment by kcrisman** [comment]
Right, what I meant was the specific piece of the comments at the bottom, sorry.

**Comment by novoselt** [comment]
Well, I think the current security goal should be "allow running notebook servers for a class without students easily cheating or accidentally messing up". While killing processes of other users will remain, hiding files with code to be executed will make it quite difficult to see what others are doing. Making memory dumps of running processes and figuring out what's inside is probably quite involved.

So - I think it is still worthwhile to use random temp dirs inside a non-readable one.
