### ISSUE TITLE
load("object.sobj") does not work anymore

### ISSUE THREAD

**Issue by novoselt** [sagemath/sagenb#336]
Because `load` in the notebook is tied to the function loading a source code file rather than objects, as it is the case on the command line.

First detected in Sage 6.5.beta5, not present in 6.4.

**Comment by novoselt** [comment]
Trac ticket http://trac.sagemath.org/ticket/17645

**Comment by kcrisman** [comment]
Could you take a look and see whether https://github.com/sagemath/sagenb/commit/98f063ecb2a708a37ff00e35198092c7f02743d6 is responsible for this?  I find it unlikely but it did change some imports.

**Comment by kcrisman** [comment]
Glad you spotted this!

**Comment by jdemeyer** [comment]
> Could you take a look and see whether 98f063e is responsible for this? I find it unlikely but it did change some imports.
No, the culprit was 2ea8adb1158ffb5048610552ad36df55fd7ee417

**Comment by kcrisman** [comment]
Aargh!  That was going to be my next guess.  My fault.
