### ISSUE TITLE
notebook.setup() buggy on OSX

### ISSUE THREAD

**Issue by dimpase** [sagemath/sagenb#341]
there is an OSX-specific bug, due to the fact that OSX's certtools is a different beast from the one on Linux. Thus generation of the public.pem fails.

**Comment by kcrisman** [comment]
Thanks.  Do you think it would be easy to raise an exception about this, or to check platform and pass platform-specific options?  I guess no one runs a public server on anything but Linux :smiley:

**Comment by dimpase** [comment]
On 12 May 2015 at 15:13, kcrisman <notifications@github.com> wrote:

> Thanks. Do you think it would be easy to raise an exception about this, or
> to check platform and pass platform-specific options? I guess no one runs a
> public server on anything but Linux [image: :smiley:]
>

I think that a fix it easy - just check that you're on OSX and call the
thing (which one? openssl?)
with the right options.

**Comment by kcrisman** [comment]
(Downstream related discussion see http://trac.sagemath.org/ticket/18397 )

**Comment by nexttime** [comment]
Isn't `certtool` (on Linux at least) part of GnuTLS Sage no longer ships?

**Comment by dimpase** [comment]
On OSX certtool has nothing to do with TLS.

**Comment by nexttime** [comment]
Well, if Sage still shipped (and installed) GnuTLS, wouldn't that fix the problem (by not using Apple's)?

Also, is `certtool` documented as a prerequisite for a secure notebook server?

**Comment by dimpase** [comment]
It's certainly an overkill to ship GnuTLS just to provide TLS's certtool. OSX has an equivalent thing, one just has to figure it out.

**Comment by nexttime** [comment]
I didn't mean it's a solution, but using the secure notebook server probably broke at some point in the past when Sage stopped shipping GnuTLS.

**Comment by dimpase** [comment]
currently the generation of private/public keys in notebook_setup() is done in 2 steps
  * `openssl genrsa` is called
  * `certtool` is called, using `---template` option `cert.cfg`

instead they can be combined in one call to openssl:
    
      $ openssl req -newkey rsa:1024 -config ssl.cfg -x509 -nodes -keyout private.pem -out public.pem

here `ssl.cfg` is an analog of `cert.cfg`, with a different format:

      [ req ]
      distinguished_name     = req_distinguished_name
      prompt                 = no

      [ req_distinguished_name ]
      C                      = GB
      ST                     = Test State or Province
      L                      = Test Locality
      O                      = Organization Name
      OU                     = Organizational Unit Name
      CN                     = Common Name
      emailAddress           = test@email.address

I checked that with these .pem files `notebook(secure=True)` works on OSX. It's easy to use this to provide a fix in sagenb. Perhaps this will work on all platforms, so a special case of OSX won't be necessary.

**Comment by ppurka** [comment]
Is the certificate accepted on all browsers? Or do we still get a big fat
scary warning that the certificate is unverified and "get out of this
website ASAP"?

**Comment by dimpase** [comment]
no, it's just a platform-neutral way to do the same thing. It's by design of SSL that you will have a warning and will have to add an exception as long as it is a self-signed cert.
