### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by kcrisman** [sagemath/sagenb#343]
As stated - see http://trac.sagemath.org/ticket/18508 among others.

**Comment by dimpase** [comment]
seems that this https://twistedmatrix.com/trac/wiki/Plan/Python3 makes this issue mere wishful thinking...

**Comment by kcrisman** [comment]
>
> seems that this https://twistedmatrix.com/trac/wiki/Plan/Python3 makes
> this issue mere wishful thinking...
>
>

Not exactly - "Last modified 39 hours ago".  But yes, I didn't think about
the sagenb dependencies needing porting to Python 3.  Rats.

**Comment by fchapoton** [comment]
please could you accept https://github.com/sagemath/sagenb/pull/373
which solves an error appearing in sage when trying to use python3 division

**Comment by fchapoton** [comment]
As Python3 for sage is getting closer, we need to handle pythyon3 here also. Or drop sagenb completely.

**Comment by dimpase** [comment]
There are some python3 patches here in the unreleased master. I don't know how many more are needed.
Did you try running sagenb in python3?
I will make a new sagenb spkg next week.

**Comment by fchapoton** [comment]
At least, this sanity check does no longer give any warning:
`
 find sagenb -name '*.py' | while read f; do python3 -m py_compile $f 2>&1 | egrep -q . && echo $f >> errors || echo $f >> noerrors ; done
`

I am afraid the latest git version may be broken somehow (maybe by my fault). I have no time to test that, but this should be done before the release.

See https://trac.sagemath.org/ticket/22431
