### ISSUE TITLE
Fix doctests

### ISSUE THREAD

**Issue by kcrisman** [sagemath/sagenb#357]
In #354 apparently problems with doctests were introduced.  @migeruhito I would be grateful if you can do something with that, otherwise I will have to see just how soon I can make time to fix them.

http://trac.sagemath.org/ticket/19616#comment:48

**Comment by migeruhito** [comment]
I go to fix it as soon as possible.  I think that it will be easy.

**Comment by migeruhito** [comment]
Done. See #358.

**Comment by kcrisman** [comment]
Closed in #358 indeed.
