### ISSUE TITLE
Broken links in live documentation

### ISSUE THREAD

**Issue by jdemeyer** [sagemath/sagenb#368]
(Note: this bug is present in sagenb-0.11.6.1 and sagenb-0.11.7 but not in sagenb-0.11.4)

In the live documentation, some links are broken, for example the link "Introduction to the p-adics" on the Thematic Tutorials page. Note that this points from the Thematic Tutorials to the Reference Manual and this doesn't seem to work.

**Comment by kcrisman** [comment]
Do you think this is a sagenb bug or a bug in the "new" (i.e. not that new any more) doc layout for Sage?  Maybe the autoescape stuff e.g. #354 had something to do with it... I can confirm for sagenb-0.11.4.  Do you notice whether there is a difference between the "italicized" and non-italicized links on the Thematic Tutorials page?

**Comment by jdemeyer** [comment]
> Do you think this is a sagenb bug or a bug in the "new" (i.e. not that new any more) doc layout for Sage?

Which "new" doc layout? The one which changed in `sagenb-0.11.7`? That cannot be the cause since the problem already appears in `sagenb-0.11.6.1`.

**Comment by jdemeyer** [comment]
Sorry, there is indeed a new doc layout now, the doc is built in `local/share/doc/sage`. I was confusing that with the introduction of the variable `SAGE_DOC_SRC`.

**Comment by kcrisman** [comment]
Right, I wasn't talking about the new variable, which you already took care of.

Do you think that is the issue?  I won't have time to look into it right away.

**Comment by jdemeyer** [comment]
It's a Sage bug, not SageNB: http://trac.sagemath.org/ticket/20118

**Comment by kcrisman** [comment]
Good.  Should we leave this open as a tracker bug or just close it?

**Comment by jdemeyer** [comment]
I would just close it.
