### ISSUE TITLE
The notebook should support running outside of the DocumentRoot

### ISSUE THREAD

**Issue by orlitzky** [sagemath/sagenb#38]
This came up in the OpenSSL discussion, and still applies to the flask notebook. Basically, right now, the notebook will only run at the document root, i.e.,

> http://localhost:8080/

It would be nice if this wasn't required, so that we could run it out of e.g.,

> http://localhost:8080/sagenb/

for two reasons:
1. Nice web applications shouldn't assume that they have control of the whole virtual host.
2. It would make an SSL reverse proxy easier in one particular case, since we could simply map,
   
   > http://math.example.edu/sagenb/ -> http://localhost:8080/sagenb/

Most other applications just define a variable in the config file called e.g. document_root that defaults to '/'. Then it's only a matter if fixing the URL-generation code to append to the document_root.

**Comment by kcrisman** [comment]
Hey, does #328 presumably deal with this?  Not perhaps in the way desired but at least by allowing proxying and renaming since there is a stable URL?
