### ISSUE TITLE
Connection refused when connecting outside the Virtual Machine

### ISSUE THREAD

**Issue by jamiechoi** [sagemath/sagenb#393]
I have a Ubuntu Server with Sage installed, and I try to connect outside the Virtual Machine with no luck.

Inside the Virtual Machine I can connect to the notebook from `localhost:8080`, but outside, I can't connect to `192.168.1.59:8080` but I can connect to `192.168.1.59` to my Apache server.

Is there any way to allow external connection to Sage notebook?

**Comment by dimpase** [comment]
Have you resolved it? Anyway, it probably has to do with the way VM networking is configured.

**Comment by jamiechoi** [comment]
Not the VM's fault, I just forgot to add the `interface=''` flag... sigh.
