### ISSUE TITLE
Is_Projective for toric varieties

### ISSUE THREAD

**Issue by HereAround** [sagemath/sagenb#402]
Hi there,

I tried to verify with Sage that P^2 is projective. Unfortunately, Sage replied with 'false'. Here is what I tried:

P2=toric_varieties.P2();
P2.is_projective()

The last line returned 'false'.  The same happens for e.g. P1xP1.

[I am running SageMath version 7.2, Release Date: 2016-05-15]

Is this a bug? Thank you!

**Comment by kcrisman** [comment]
Hi!  This is the github for the Sage notebook server, and has nothing to do (per se) with Sage computations.  I recommend you ask on sage-support@googlegroups.com, [ask sage](http://ask.sagemath.org), or conceivably even open an issue on the Sage github site (https://github.com/sagemath/sage) though I'm not sure how actively that is connected to our development model.

**Comment by kcrisman** [comment]
I posted your question there at https://groups.google.com/forum/#!topic/sage-support/Hig4aTjkBwk - please follow along there, hopefully you get an answer!  (It does seem odd to me but remember that `is_projective` is not necessarily saying whether your variety is projective, but something about the ambient space: the code for it in this case is simply `return False`!)

**Comment by HereAround** [comment]
My sincere apologies for posting the question in the wrong place. Also thank you very much for (a) posting the problem at the appropriate place and (b) providing answers already.

**Comment by kcrisman** [comment]
> My sincere apologies for posting the question in the wrong place. Also
> thank you very much for (a) posting the problem at the appropriate place
> and (b) providing answers already.
>
>

No problem, though I don't know how useful my answer there is.
