### ISSUE TITLE
"Use java for 3-D" does not work

### ISSUE THREAD

**Issue by infinity0** [sagemath/sagenb#415]
This was originally implemented in https://trac.sagemath.org/ticket/16004. However, it does not work - specifically the 0001-Add-option-to-use-java-for-3D.patch.

Firstly, 3D_use_java_check is not a valid JS identifier because it starts with a digit, and clicking on that checkbox gives a SyntaxError in my browser console. Secondly, even if it was a valid identifier, it is not defined anywhere!

The intention seems to have been to mimic the live-3d thing. Both live_3D_check and pretty_print_check are defined in notebook_lib.js and send an async_request back to the server. There is no analog for 3D_java_check, even in the current version.

**Comment by infinity0** [comment]
It seems to me that this was never tested and is not meant to work. For example nothing else references the "jarFile" that is given in jmol_lib.js. Could someone please confirm this, and either fix the support or just remove the "Use Java for 3D" button since it misleads users?

**Comment by kcrisman** [comment]
I don't know about your details, but I have definitely (successfully) used this particular check box on multiple occasions - not just while testing.  Not for quite some time, granted.

**Comment by infinity0** [comment]
Could you try it in the current version? I can't see how could have possibly ever worked, given the code. @gutow could you elaborate? I have found the github PR, it was #241 .

**Comment by gutow** [comment]
The option to use Java for 3-D **should probably be removed**. MacOS and I believe Windows are both making it difficult to impossible to install an updated Java VM and plugin. Thus the operating systems have a tendency to block any in browser Java. I have only been able to keep my Linux machines properly up-to-date in Java. I would call this an unfair marketing practice, but will simply stop using Macs and Windows machines as they do not allow me to use the tools I need to use.

**Comment by gutow** [comment]
This definitely worked well when I implemented it. However, I have not worked on the code in a while. Pieces may have been removed. That said, I still think we should give up on it.

**Comment by infinity0** [comment]
Understood, thanks for the update! I've removed that checkbox from the Debian package, I'll forward these patches when I get some time.

We're somewhat interested in Java 3D, if it wouldn't be too hard to fix again - because JSmol packaging is not going to be easily achieved any time soon. However I understand that Java only works in Firefox because Chrome only supports PPAPI plugins now and Java doesn't yet have it. So the cost-benefit ratio here is quite low. But you can contact me again if you change your mind and want testers.

On a related note, I think SageMath should try to find other 3D browser viewers apart from JSmol, for the sake of software packagers and FOSS distributions, but I will email sage-devel@ about this separately.

**Comment by kcrisman** [comment]
>  I've removed that checkbox from the Debian package, I'll forward these patches when I get some time.

Thanks!

We're open to Java 3d too but keep in mind that the sagenb is currently in maintenance mode.  Also, Sage will have three.js support in the next version (not necessarily in the notebook) and this apparently works more or less in several of the replacement notebooks, from what I hear.  We also have long supported tachyon and another rotatable viewer whose name escapes me this instant.

**Comment by infinity0** [comment]
Understood, looking forward to it! That doesn't seem too bad to package. Yes, I've been told that the other viewers (canvas3d is I think the other one you mean) do work in SageNB Debian, but in their opinion less well than JSmol, unfortunately.
