### ISSUE TITLE
Doctesting SageNB creates a directory "home" in SAGE_ROOT

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sagenb#425]
Doctesting the file sagenb/storage/filesystem_storage.py leads to creation of a directory "home" in SAGE_ROOT, I think because of the doctest on line 179:

`    sage: D = FilesystemDatastore("")`

`FilesystemDatastore` should be called with argument `tmp_dir()` instead.

**Comment by kcrisman** [comment]
Good catch.

**Comment by jhpalmieri** [comment]
Here is the required change:
```
diff --git a/sagenb/storage/filesystem_storage.py b/sagenb/storage/filesystem_storage.py
index 13ec61b..91663ab 100644
--- a/sagenb/storage/filesystem_storage.py
+++ b/sagenb/storage/filesystem_storage.py
@@ -194,7 +194,7 @@ class FilesystemDatastore(Datastore):
         Check that interrupting ``_save`` is safe::
 
             sage: from sagenb.storage.filesystem_storage import FilesystemDatastore
-            sage: D = FilesystemDatastore("")
+            sage: D = FilesystemDatastore(tmp_dir())
             sage: fn = tmp_filename()
             sage: s = "X" * 100000
             sage: D._save(s, fn)
```
I've forgotten how to do pull requests here and I don't feel like plumbing the depths of git and github right now; can someone else take care of it?

**Comment by kcrisman** [comment]
See #427 - I think this must have just been an oversight, because there are quite a few others that are correct in that file.

@dimpase if you are okay with this easy change just go ahead and merge it before you make the release for Sage.

**Comment by jhpalmieri** [comment]
Great, thanks! Should we close this issue now?

**Comment by kcrisman** [comment]
Yup - thanks for noticing it!
