### ISSUE TITLE
unicode error when python mode is selected

### ISSUE THREAD

**Issue by kcrisman** [sagemath/sagenb#426]
See https://ask.sagemath.org/question/26167/unicodedecodeerror-in-notebook-server-if-worksheet-is-set-to-python-instead-of-sage/

**Comment by dimpase** [comment]
does conversion from sagenb work for such plain python sheets?

**Comment by kcrisman** [comment]
Don't know, but in principle this could be an enhancement request...

**Comment by dimpase** [comment]
regarding the original request, yes, in principle the error looks trivial to fix. It probably amounts to adding few `encode('utf-8')` and `decode('utf-8')` around [here. ](https://github.com/sagemath/sagenb/blob/master/sagenb/storage/filesystem_storage.py#L512)
