### ISSUE TITLE
delete users

### ISSUE THREAD

**Issue by msambg** [sagemath/sagenb#432]
If I manage Users from the Admin account, I get an 500: Internal Server error when I delete users or suspend users. Anyway the users are deleted or suspended in the notebook gui, but the directories are not deleted!

Can I delete the user symlinks and user directories manually?

What's wrong with my installation?

**Comment by msambg** [comment]
I also get the error after publishing a worksheet.
This happens with V8.0
I changed the Version back to 7.5.1. here everything works.

**Comment by msambg** [comment]
But: A General question:
Is it normal, if I delete a user in the gui, he vanishes from the list in the gui, 
but on the harddisk his directory is still there and also the symbolic link to the directory and all his worksheets.
How can I delete a user completeley, including all directories and worksheets?

**Comment by kcrisman** [comment]
Possibly same as https://groups.google.com/forum/#!topic/sage-devel/1cBRR4nfaqE

**Comment by kcrisman** [comment]
@fchapoton could #422 have caused this?  (I don't understand exactly how all the routing functions import, in what order, etc.)  See https://groups.google.com/forum/#!topic/sage-devel/1cBRR4nfaqE for more discussion of a related issue, perhaps you have ideas, thanks!

**Comment by dimpase** [comment]
I don't think anyone works on fixing this --- it's certainly not a priority, given that sagenb is to be retired in the not so distant future of switching to python3.
