### ISSUE TITLE
Upload of data files does not work.

### ISSUE THREAD

**Issue by kapilhp** [sagemath/sagenb#435]
Currently the upload of data files via the "Data Upload" interface produces an error.

The relevant portion from the server standard error is attached.
[error_upload.txt](https://github.com/sagemath/sagenb/files/1429813/error_upload.txt)

More later.

**Comment by kcrisman** [comment]
> The relevant portion from the server standard error is attached.
>

Yet another one of these "unable to build" errors.  I wish we knew exactly
what the story was with these.

**Comment by kcrisman** [comment]
Seems like #458 might be a way to solve this.

**Comment by ivoks** [comment]
I'll take a look at this next week if no one solves it before then.
