### ISSUE TITLE
Help importing challenge.py in Sage

### ISSUE THREAD

**Issue by pguerr061703** [sagemath/sagenb#444]
Hello,
I'm running Sage 6.5  on a Redhat 6 virtual host. I need to have a CAPTCHA on the login screen of my Sage site. Can someone please assist me with this request. How do I do that? What command can I run? Any help would be greatly appreciated.  thank you

**Comment by kcrisman** [comment]
Probably this makes more sense at ask.sagemath.org ... anyway, see `sagenb/notebook/server_conf.py` and so in the admin configuration file you would change these

            'challenge':False,
            'challenge_type':'simple'

Easiest is to do this by simply being admin in the notebook and going to http://localhost:8080/notebooksettings - you can reach this from "Settings" at the top.

**Comment by embray** [comment]
Unless there's a specific problem (e.g. a bug) preventing this I wouldn't have an open issue about that here.
