### ISSUE TITLE
"new worksheet" opens with data from an old worksheet (0.10.0-1)

### ISSUE THREAD

**Issue by gutow** [sagemath/sagenb#87]
Installed in sage 5.2.beta1 as per sage trac#13121 creating a new worksheet generates a worksheet named "untitled" with the contents of another worksheet in it rather than being empty.

**Comment by kcrisman** [comment]
> Wasn't this fixed?

The problem is that it's very hard to tell if it was fixed *for sure* when no one ever identified a specific fix and a lack of reports doesn't mean it is fixed.  However, it probably (?) is.  Even these ideas are still useful, of course.
